### ISSUE TITLE
Duplicate tables breaks install

### ISSUE THREAD

**Issue by jwest-aca** [place-labs/development-environment#3]
Found the ./install script will continue after asking for GitLab credentials, if this happens, the install script will fail to complete.

Install script requesting GitLab Auth:
`Cloning into '/Users/jeremywest/Documents/Code/ACA/placeos/development-environment/dockerfiles/crystal'...
Username for 'https://gitlab.com': Cloning into '/Users/jeremywest/Documents/Code/ACA/placeos/development-environment/dockerfiles/play'...
Cloning into '/Users/jeremywest/Documents/Code/ACA/placeos/development-environment/dockerfiles/rethinkdb'...`

Install script fails here:
`Cloning into './placeos/development-environment/monitor-host'...`

Following this issue, stopping the install script and restarting the script will then prompt for GitLab credentials, but will fail to create user entity correctly:
`=== Waiting until auth container is up and running... done

=== Initiating engine with default domain (localhost:8080)...
/app/app/models/authority.rb:41: warning: already initialized constant Authority::DEFAULT_BUCKET
/app/app/models/authority.rb:41: warning: previous definition of DEFAULT_BUCKET was here
/app/app/models/user.rb:14: warning: already initialized constant User::PUBLIC_DATA
/app/app/models/user.rb:14: warning: previous definition of PUBLIC_DATA was here
Connected to rethinkdb://rethink:28015/place_development

Failed to create user entity`

At this point, all containers will be up but auth container will be in a reboot loop.

**Comment by caspiano** [comment]
let's move that repo over to place-labs @qk4

**Comment by caspiano** [comment]
this is a [nobrainer](https://github.com/nviennot/nobrainer) issue.
I made a fix in the crystal [rethinkdb-orm](https://github.com/spider-gazelle/rethinkdb-orm/blob/master/src/rethinkdb-orm/connection.cr#L155).
